version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./crayons-frontend/:/data/
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - crayons

networks:
  crayons:
    name: crayons
    driver: bridge
